In [3]:
import pandas as pd
import os
import sys
import pickle
import argparse
import numpy as np
import matplotlib.pyplot as plt

In [4]:
FLOPS = {
    100: 1,
    2: 2090524455 / 161264981936,
    6: 5211827866 / 161264981936,
    15: 12069704997 / 161264981936,
    30: 23823782173 / 161264981936,
    50: 34933622501 / 161264981936,
    70: 48105020743 / 161264981936,
}

In [5]:
flops = [2,6,15,30, 50, 70, 100]

In [6]:
np.log(flops)

array([0.69314718, 1.79175947, 2.7080502 , 3.40119738, 3.91202301,
       4.24849524, 4.60517019])

In [7]:
if not []:
    print("dog")

dog


In [53]:
results_file = os.path.join("./results/20250129_023617", "data", "optimization_results_new.pickle")


In [54]:
with open(results_file, 'rb') as f:
    data = pickle.load(f)

all_results = data['all_results']

In [60]:
df = data['all_results'][('RandomSearch',1,38)]['history']

In [62]:
df

z      func                                            history  \
0   196  2.766234  [(1.0, 5.951281252726038), (2.0, 5.56293412710...   
1   196  2.706471  [(1.0, 5.508005135358881), (2.0, 5.11718070619...   
2   196  2.696188  [(1.0, 5.80628752132036), (2.0, 5.410795801207...   
3   196  2.516730  [(1.0, 5.128189702658916), (2.0, 4.45245896100...   
4   196  2.653017  [(1.0, 5.310325961021862), (2.0, 4.89282937229...   
..  ...       ...                                                ...   
77  196  2.819786  [(1.0, 6.0308124863878625), (2.0, 5.6302262255...   
78  196  2.666881  [(1.0, 5.3212507135598415), (2.0, 4.8998686175...   
79  196  2.563557  [(1.0, 5.3530374549860555), (2.0, 4.8913358604...   
80  196  2.813007  [(1.0, 5.986281146230738), (2.0, 5.57416588224...   
81  196  2.663282  [(1.0, 5.7251352571348635), (2.0, 5.3046165283...   

                                                    x  
0   -0.6913612828995372|2.158247079543714|2.665197...  
1   0.6357676919435882|-1.7992389428405733|-0.6756...  
2   -1.3142581519332552|-0.36939509312370156|-0.10...  
3   0.37357886540853524|-0.17366793602885533|1.133...  
4   2.7622029239195163|2.1488654322907585|-1.14494...  
..                                                ...  
77  -1.2675325502409036|-0.9877546617408974|1.5705...  
78  1.3926955941915633|0.8227408827290628|-2.80447...  
79  -0.5259369232969835|-0.35961620238686187|-0.24...  
80  -1.5292040784424705|1.2096211018237808|2.52612...  
81  -1.7168655919777167|-0.2150252342836465|-0.629...  

[82 rows x 4 columns]

In [69]:
196*82

16072

In [64]:
for row in df.itertuples():
    for _, val in row.history:
        print(val)

5.951281252726038
5.562934127100337
5.093228827394392
4.619153484788746
4.413446396213353
4.227821463789588
4.0470047757060446
3.9327037674787397
3.8644327102036793
3.8127555784085203
3.76142992114731
3.7212950055409144
3.6868511662976307
3.6434715403940614
3.604985145435098
3.5646181156385652
3.5228632336423207
3.4913609263192074
3.464688855435325
3.442427286705872
3.4207719527984244
3.399946089036535
3.3800748530764038
3.3636200298396743
3.3475839986859244
3.331547812345992
3.315129513285791
3.2978074098986068
3.277894672719379
3.256309826592977
3.2352389571030735
3.2182748239000487
3.2018167971771234
3.1835983383997157
3.166861952004263
3.1510313208478022
3.134439878346821
3.120437739470604
3.1083722798133
3.098471578724301
3.088570921974211
3.0786701765463027
3.071078734530987
3.065926686288124
3.0612331467062366
3.0563909387614974
3.0519941594994933
3.0465499178444033
3.0412161244123572
3.036477935548814
3.0316098336810486
3.0267110492880542
3.02181226489506
3.0169134805020654
3.0

In [38]:
all_results[('RandomSearch',1,38)]["history"].loc[0, 'x']

'-0.6913612828995372|2.158247079543714|2.66519781484452|1.2169493616643763|0.8018045830284413'

In [45]:
df = all_results[('RandomSearch',1,38)]["history"]

In [48]:
df['history']

0     [(1.0, 5.951281252726038), (2.0, 5.56293412710...
1     [(1.0, 5.508005135358881), (2.0, 5.11718070619...
2     [(1.0, 5.80628752132036), (2.0, 5.410795801207...
3     [(1.0, 5.128189702658916), (2.0, 4.45245896100...
4     [(1.0, 5.310325961021862), (2.0, 4.89282937229...
                            ...                        
77    [(1.0, 6.0308124863878625), (2.0, 5.6302262255...
78    [(1.0, 5.3212507135598415), (2.0, 4.8998686175...
79    [(1.0, 5.3530374549860555), (2.0, 4.8913358604...
80    [(1.0, 5.986281146230738), (2.0, 5.57416588224...
81    [(1.0, 5.7251352571348635), (2.0, 5.3046165283...
Name: history, Length: 82, dtype: object

In [46]:
df['history'].str.split('|').apply(lambda x: [tuple(map(float, i.split(':'))) for i in x])

TypeError: 'float' object is not iterable

In [15]:
min_vals = [1,2]
max_vals = [1.5,2.2]

In [16]:
np.array([np.random.uniform(min_val, max_val) for min_val, max_val in zip(min_vals, max_vals)]).reshape(1, -1)

array([[1.48473043, 2.11886216]])

In [17]:
[[-3.0, 3.0] for i in range(5)]

[[-3.0, 3.0], [-3.0, 3.0], [-3.0, 3.0], [-3.0, 3.0], [-3.0, 3.0]]

In [ ]:
if not os.path.exists(results_file):
    print(f"Error: Could not find results file at {results_file}")
    print(f"Current working directory: {os.getcwd()}")
    print(f"Please make sure the path to results directory is correct")
    sys.exit(1)

with open(results_file, 'rb') as f:
    data = pickle.load(f)

all_results = data['all_results']
config = data['config']

In [49]:
fname = "hmf_history.npy"

arr = np.load(fname, allow_pickle=True)

In [68]:
arr.shape


(15, 5)

In [8]:
A =[]

In [9]:
A.append((0,1))

In [6]:
A.remove((0,1))

In [7]:
A

[]

In [11]:
a,b =min(A, key=lambda t: t[1])

In [54]:
import random
points = {(0, 1): 'A', (2, -3): 'B', (4, 0): 'C', (-1, 5): 'D'}

random_point = random.choice(list(points)) 

In [55]:
list(points)

[(0, 1), (2, -3), (4, 0), (-1, 5)]

In [58]:
a = set()
a.add(1)

array({1}, dtype=object)

In [11]:
import numpy as np
import pandas as pd

In [38]:
search_space = [(0, 1) for i in range(2)]

In [41]:
grids = [np.linspace(min_val, max_val, 5) for min_val, max_val in search_space]

# Create a meshgrid to find all combinations of values
mesh = np.meshgrid(*grids)
points = np.stack(mesh, axis=-1).reshape(-1, len(search_space))

In [48]:
points[2]

array([0.5, 0. ])

In [44]:
search_space

[(0, 1), (0, 1)]

In [42]:
mesh

[array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]])]

In [43]:
np.stack(mesh, axis=-1)

array([[[0.  , 0.  ],
        [0.25, 0.  ],
        [0.5 , 0.  ],
        [0.75, 0.  ],
        [1.  , 0.  ]],

       [[0.  , 0.25],
        [0.25, 0.25],
        [0.5 , 0.25],
        [0.75, 0.25],
        [1.  , 0.25]],

       [[0.  , 0.5 ],
        [0.25, 0.5 ],
        [0.5 , 0.5 ],
        [0.75, 0.5 ],
        [1.  , 0.5 ]],

       [[0.  , 0.75],
        [0.25, 0.75],
        [0.5 , 0.75],
        [0.75, 0.75],
        [1.  , 0.75]],

       [[0.  , 1.  ],
        [0.25, 1.  ],
        [0.5 , 1.  ],
        [0.75, 1.  ],
        [1.  , 1.  ]]])

In [31]:
grids

[array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])]

In [49]:
x_func_found = []

In [ ]:
x_func_found

In [52]:
tuple([1,2,3])[1]

2

In [ ]:
explored = {tuple(p[0]) for p in x_func_found}

In [33]:
np.meshgrid(np.array([1,2]),np.array([3,4,5]))

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[3, 3],
        [4, 4],
        [5, 5]])]

In [27]:
grids

[array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])]

In [12]:
pd.DataFrame(grids).shape

(5, 10)

In [17]:
len(mesh)

5

In [24]:
len(mesh[0][0][0][0])

10

In [25]:
mesh[0][0][0][0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])